import type { CardColor, MatchEvent, MatchEventType } from "../types/match-event";
import type { ApiClient } from "./client";

export interface ListMatchEventsResponse {
  matchEvents: MatchEvent[];
}

export interface MatchEventResponse {
  matchEvent: MatchEvent;
}

export interface CreateMatchEventInput {
  // FR27: generated by the caller, not the server — see client.ts's
  // ApiRequestError/retry handling and match-event.model.ts for why this
  // makes resubmitting a failed/uncertain submission safe.
  client_event_id: string;
  type: MatchEventType;
  minute: number;
  team_id: string;
  player_id?: string | null;
  card_color?: CardColor | null;
  details?: Record<string, unknown>;
}

export function createMatchEventsApi(client: ApiClient) {
  return {
    /** FR26/FR39: shared between the assigned reporter and a verifier reviewing before confirming — see match-event.service.ts. */
    list: (fixtureId: string) => client.get<ListMatchEventsResponse>(`/fixtures/${fixtureId}/events`),
    /** FR26/FR27: idempotent on client_event_id — a retried submission returns the original event (200), a new one 201. */
    create: (fixtureId: string, input: CreateMatchEventInput) =>
      client.post<MatchEventResponse>(`/fixtures/${fixtureId}/events`, input),
  };
}

export type MatchEventsApi = ReturnType<typeof createMatchEventsApi>;
