import { MATCH_EVENT_TYPES, type MatchEventType } from "@leaguelive/shared";
import { Schema, Types, model, type Document } from "mongoose";
import { withBaseOptions } from "./plugins/schema-options";

export interface MatchEventAttrs {
  organization_id: Types.ObjectId;
  fixture_id: Types.ObjectId;
  // FR27: generated by the reporter app, not the server — see
  // match-event.service.ts's createMatchEvent for the idempotency this enables.
  client_event_id: string;
  type: MatchEventType;
  minute: number;
  team_id: Types.ObjectId;
  player_id: Types.ObjectId | null;
  details: Record<string, unknown>;
}

export interface MatchEventDocument extends MatchEventAttrs, Document {}

function isPlainObject(value: unknown): boolean {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const matchEventSchema = new Schema<MatchEventDocument>(
  {
    organization_id: {
      type: Schema.Types.ObjectId,
      ref: "Organization",
      required: true,
      index: true,
    },
    fixture_id: {
      type: Schema.Types.ObjectId,
      ref: "Fixture",
      required: true,
      index: true,
    },
    client_event_id: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 100,
    },
    type: {
      type: String,
      required: true,
      enum: MATCH_EVENT_TYPES,
    },
    minute: {
      type: Number,
      required: true,
      min: 0,
    },
    team_id: {
      type: Schema.Types.ObjectId,
      ref: "Team",
      required: true,
    },
    player_id: {
      type: Schema.Types.ObjectId,
      ref: "Player",
      default: null,
    },
    details: {
      type: Schema.Types.Mixed,
      default: () => ({}),
      validate: { validator: isPlainObject, message: "details must be an object" },
    },
  },
  withBaseOptions<MatchEventDocument>(),
);

// FR27: the idempotency key — a retried submission with the same
// (fixture_id, client_event_id) must resolve to the same event, never a
// duplicate.
matchEventSchema.index({ fixture_id: 1, client_event_id: 1 }, { unique: true });

export const MatchEvent = model<MatchEventDocument>("MatchEvent", matchEventSchema);
