import { CARD_COLORS, MATCH_EVENT_TYPES, type CardColor, type MatchEventType } from "@leaguelive/shared";
import { Schema, Types, model, type Document } from "mongoose";
import { withBaseOptions } from "./plugins/schema-options";

export interface MatchEventAttrs {
  organization_id: Types.ObjectId;
  fixture_id: Types.ObjectId;
  // FR27: generated by the reporter app, not the server — see
  // match-event.service.ts's createMatchEvent for the idempotency this enables.
  client_event_id: string;
  type: MatchEventType;
  minute: number;
  team_id: Types.ObjectId;
  player_id: Types.ObjectId | null;
  // Required when type is "card" (FR41 needs it to be reliable), null otherwise.
  card_color: CardColor | null;
  details: Record<string, unknown>;
}

export interface MatchEventDocument extends MatchEventAttrs, Document {}

function isPlainObject(value: unknown): boolean {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const matchEventSchema = new Schema<MatchEventDocument>(
  {
    organization_id: {
      type: Schema.Types.ObjectId,
      ref: "Organization",
      required: true,
      index: true,
    },
    fixture_id: {
      type: Schema.Types.ObjectId,
      ref: "Fixture",
      required: true,
      index: true,
    },
    client_event_id: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 100,
    },
    type: {
      type: String,
      required: true,
      enum: MATCH_EVENT_TYPES,
    },
    minute: {
      type: Number,
      required: true,
      min: 0,
    },
    team_id: {
      type: Schema.Types.ObjectId,
      ref: "Team",
      required: true,
    },
    player_id: {
      type: Schema.Types.ObjectId,
      ref: "Player",
      default: null,
    },
    card_color: {
      type: String,
      enum: CARD_COLORS,
      default: null,
    },
    details: {
      type: Schema.Types.Mixed,
      default: () => ({}),
      validate: { validator: isPlainObject, message: "details must be an object" },
    },
  },
  withBaseOptions<MatchEventDocument>(),
);

// FR27: the idempotency key — a retried submission with the same
// (fixture_id, client_event_id) must resolve to the same event, never a
// duplicate.
matchEventSchema.index({ fixture_id: 1, client_event_id: 1 }, { unique: true });

// FR41 needs card severity to actually be present on every card event, and
// nonsensical on every non-card event — a cross-field rule Mongoose's
// per-field `enum`/`required` can't express on its own.
matchEventSchema.pre("validate", function enforceCardColor(next) {
  if (this.type === "card" && !this.card_color) {
    this.invalidate("card_color", "card_color is required for a card event");
  }
  if (this.type !== "card" && this.card_color) {
    this.invalidate("card_color", "card_color may only be set for a card event");
  }
  next();
});

export const MatchEvent = model<MatchEventDocument>("MatchEvent", matchEventSchema);
