// FR26: the event types a Reporter logs in real time.
export const MATCH_EVENT_TYPES = ["goal", "card", "substitution", "half_time", "full_time"] as const;

export type MatchEventType = (typeof MATCH_EVENT_TYPES)[number];

// FR41 needs card severity to be reliable (yellow vs red materially changes
// a disciplinary record), so — unlike substitution details, which stay in
// the unstructured `details` bag — this is a first-class, validated field
// rather than a loosely-typed convention inside `details`.
export const CARD_COLORS = ["yellow", "red"] as const;

export type CardColor = (typeof CARD_COLORS)[number];

// FR27: `client_event_id` is generated by the reporter app before
// submission, not by the server — the reporter app queues events locally
// and retries them on reconnect, so the server must treat a resubmission of
// the same client_event_id as a no-op rather than creating a duplicate.
export interface MatchEvent {
  id: string;
  organization_id: string;
  fixture_id: string;
  client_event_id: string;
  type: MatchEventType;
  minute: number;
  // Which of the fixture's two teams (by Team id) this event is attributed to.
  team_id: string;
  player_id: string | null;
  // Required when type is "card", null otherwise.
  card_color: CardColor | null;
  // Type-specific data (e.g. substitute player id) — deliberately
  // unstructured, same reasoning as Competition's ruleset/format.config:
  // FR26 doesn't specify a fixed per-type shape.
  details: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}
