// FR26: the event types a Reporter logs in real time.
export const MATCH_EVENT_TYPES = ["goal", "card", "substitution", "half_time", "full_time"] as const;

export type MatchEventType = (typeof MATCH_EVENT_TYPES)[number];

// FR27: `client_event_id` is generated by the reporter app before
// submission, not by the server — the reporter app queues events locally
// and retries them on reconnect, so the server must treat a resubmission of
// the same client_event_id as a no-op rather than creating a duplicate.
export interface MatchEvent {
  id: string;
  organization_id: string;
  fixture_id: string;
  client_event_id: string;
  type: MatchEventType;
  minute: number;
  // Which of the fixture's two teams (by Team id) this event is attributed to.
  team_id: string;
  player_id: string | null;
  // Type-specific data (e.g. card color, substitute player id) —
  // deliberately unstructured, same reasoning as Competition's ruleset/
  // format.config: FR26 doesn't specify a fixed per-type shape.
  details: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}
